name: gitlab-admin

services:
  gitlab-admin:
    build:
      context: .
      dockerfile: Dockerfile.compose
    user: 1000:1000
    # docker in docker
    group_add:
      - docker
    volumes:
      - ./:/app
      # docker in docker
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
